Addressed review comments.
Signed-off-by: Shriya Deshmukh <shriya.deshmukh@seagate.com>

diff --git a/src/setup/rgw_service b/src/setup/rgw_service
--- a/src/setup/rgw_service
+++ b/src/setup/rgw_service
@@ -14,12 +14,33 @@
 # For any questions about this software or licensing,
 # please email opensource@seagate.com or cortx-questions@seagate.com.
 
-index=$1
+while [ $# -gt 0 ];  do
+    case $1 in
+    -i )
+        shift 1
+        index=$1
+        ;;
+    -c )
+        shift 1
+        rgw_config_file=$1
+        ;;
+    -l )
+        shift 1
+        log_file=$1
+        ;;
+    * )
+        echo -e "Invalid argument provided : $1"
+        show_usage
+        exit 1
+        ;;
+    esac
+    shift 1
+done
 
 function start_rgw {
   machine_id=$(cat /etc/machine-id)
   # TODO: To use log dir from config
-  exec sudo /usr/bin/radosgw -f --name client.rgw-"$index" -c /etc/cortx/rgw/"$machine_id"/cortx_rgw.conf --no-mon-config &> /var/log/ceph/rgw.log &
+  exec sudo /usr/bin/radosgw -f --name client.rgw-"$index" -c "$rgw_config_file" --no-mon-config &> "$log_file" &
 }
 
 start_rgw
